pub enum Arg {
    RelPos8,
    RelPos16,
    Imm8,
    Imm16,
}

pub enum Special {
    None,
    Invalid,
    Ret,
    Jump,
    KCall,
    CallI,
    Call0,
    CallE
}

pub struct Opcode {
    pub name: &'static str,
    pub arg: &'static [Arg],
    pub special: Special
}

pub static OPCODES: [Opcode; 256] = [
    Opcode{ name: "bnot.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "bnot.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "add.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "add.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "sub.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "sub.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "mul.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "mul.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "div.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "div.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "mod.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "mod.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "shr.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "shr.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "shl.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "shl.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "xor.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "xor.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "and.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "and.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "or.w",                 arg: &[ ],                                      special: Special::None },
    Opcode{ name: "or.b",                 arg: &[ ],                                      special: Special::None },
    Opcode{ name: "neg.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "neg.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "not.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "not.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "eq?.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "eq?.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ne?.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ne?.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "gt?.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "gt?.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ge?.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ge?.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "lt?.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "lt?.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "le?.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "le?.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ugt?.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ugt?.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "uge?.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "uge?.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ult?.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ult?.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ule?.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ule?.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "bt.w",                 arg: &[ Arg::RelPos16 ],                        special: Special::Jump },
    Opcode{ name: "bt.b",                 arg: &[ Arg::RelPos8 ],                         special: Special::Jump },
    Opcode{ name: "bnt.w",                arg: &[ Arg::RelPos16 ],                        special: Special::Jump },
    Opcode{ name: "bnt.b",                arg: &[ Arg::RelPos8 ],                         special: Special::Jump },
    Opcode{ name: "jmp.w",                arg: &[ Arg::RelPos16 ],                        special: Special::Jump },
    Opcode{ name: "jmp.b",                arg: &[ Arg::RelPos8 ],                         special: Special::Jump },
    Opcode{ name: "ldi.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ldi.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "push.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "push.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "pushi.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "pushi.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "toss.w",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "toss.b",               arg: &[ ],                                      special: Special::None },
    Opcode{ name: "dup.w",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "dup.b",                arg: &[ ],                                      special: Special::None },
    Opcode{ name: "link.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "link.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "call.w",               arg: &[ Arg::RelPos16, Arg::Imm8 ],             special: Special::CallI },
    Opcode{ name: "call.b",               arg: &[ Arg::RelPos8, Arg::Imm8 ],              special: Special::CallI },
    Opcode{ name: "callk.w",              arg: &[ Arg::Imm16, Arg::Imm8 ],                special: Special::KCall },
    Opcode{ name: "callk.b",              arg: &[ Arg::Imm8, Arg::Imm8 ],                 special: Special::KCall },
    Opcode{ name: "callb.w",              arg: &[ Arg::Imm16, Arg::Imm8 ],                special: Special::Call0 },
    Opcode{ name: "callb.b",              arg: &[ Arg::Imm8, Arg::Imm8 ],                 special: Special::Call0 },
    Opcode{ name: "calle.w",              arg: &[ Arg::Imm16, Arg::Imm16, Arg::Imm8 ],    special: Special::CallE },
    Opcode{ name: "calle.b",              arg: &[ Arg::Imm8, Arg::Imm8, Arg::Imm8 ],      special: Special::CallE },
    Opcode{ name: "ret.w",                arg: &[ ],                                      special: Special::Ret },
    Opcode{ name: "ret.b",                arg: &[ ],                                      special: Special::Ret },
    Opcode{ name: "send.w",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "send.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "?4c",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "?4d",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "?4e",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "?4f",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "class.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "class.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "?52",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "?53",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "self.w",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "self.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "super.w",              arg: &[ Arg::Imm16, Arg::Imm8 ],                special: Special::None },
    Opcode{ name: "super.b",              arg: &[ Arg::Imm8, Arg::Imm8 ],                 special: Special::None },
    Opcode{ name: "&rest.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "&rest.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lea.w",                arg: &[ Arg::Imm16, Arg::Imm16 ],               special: Special::None },
    Opcode{ name: "lea.b",                arg: &[ Arg::Imm8, Arg::Imm8 ],                 special: Special::None },
    Opcode{ name: "selfid.w",             arg: &[ ],                                      special: Special::None },
    Opcode{ name: "selfid.b",             arg: &[ ],                                      special: Special::None },
    Opcode{ name: "?5e",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "?5f",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "pprev.w",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "pprev.b",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "ptoa.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ptoa.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "atop.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "atop.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ptos.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ptos.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "stop.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "stop.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "iptoa.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "iptoa.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "dptoa.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "dptoa.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "iptos.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "iptos.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "dptos.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "dptos.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lofsa.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lofsa.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lofss.w",              arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lofss.b",              arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "push0.w",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "push0.b",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "push1.w",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "push1.b",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "push2.w",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "push2.b",              arg: &[ ],                                      special: Special::None },
    Opcode{ name: "pushself.w",           arg: &[ ],                                      special: Special::None },
    Opcode{ name: "pushself.b",           arg: &[ ],                                      special: Special::None },
    Opcode{ name: "?7e",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "?7f",                  arg: &[ ],                                      special: Special::Invalid },
    Opcode{ name: "lag.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lag.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lal.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lal.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lat.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lat.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lap.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lap.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lsg.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lsg.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lsl.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lsl.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lst.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lst.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lsp.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lsp.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lagi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lagi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lali.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lali.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lati.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lati.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lapi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lapi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lsgi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lsgi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lsli.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lsli.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lsti.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lsti.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "lspi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "lspi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sag.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sag.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sal.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sal.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sat.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sat.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sap.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sap.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ssg.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ssg.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ssl.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ssl.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sst.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sst.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ssp.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ssp.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sagi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sagi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sali.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sali.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sati.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sati.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sapi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sapi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ssgi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ssgi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ssli.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ssli.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "ssti.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "ssti.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "sspi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "sspi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+ag.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+ag.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+al.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+al.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+at.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+at.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+ap.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+ap.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+sg.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+sg.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+sl.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+sl.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+st.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+st.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+sp.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+sp.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+agi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+agi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+ali.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+ali.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+ati.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+ati.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+api.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+api.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+sgi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+sgi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+sli.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+sli.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+sti.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+sti.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "+spi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "+spi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-ag.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-ag.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-al.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-al.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-at.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-at.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-ap.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-ap.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-sg.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-sg.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-sl.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-sl.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-st.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-st.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-sp.w",                arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-sp.b",                arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-agi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-agi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-ali.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-ali.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-ati.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-ati.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-api.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-api.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-sgi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-sgi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-sli.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-sli.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-sti.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-sti.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
    Opcode{ name: "-spi.w",               arg: &[ Arg::Imm16 ],                           special: Special::None },
    Opcode{ name: "-spi.b",               arg: &[ Arg::Imm8 ],                            special: Special::None },
];
